### ISSUE TITLE
Conversion fails

### ISSUE THREAD

**Issue by dryBoneMarrow** [rbodziony/mcf2pdf#34]
The conversion fails always on the same page, this page contains an image, some text and a table. This is the whole output inclusive the error message:
```[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 0+1...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 2+3...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 4+5...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 6+7...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 8+9...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 10+11...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.ClassCastException: class org.jsoup.nodes.Element cannot be cast to class org.jsoup.nodes.TextNode (org.jsoup.nodes.Element and org.jsoup.nodes.TextNode are in unnamed module of loader 'app')
	at net.sf.mcf2pdf.pagebuild.PageText.parseText(PageText.java:158)
	at net.sf.mcf2pdf.pagebuild.PageText.<init>(PageText.java:61)
	at net.sf.mcf2pdf.Mcf2FoConverter.processDoublePage(Mcf2FoConverter.java:296)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:253)
	at net.sf.mcf2pdf.Main.main(Main.java:212)```

**Comment by rbodziony** [comment]
Hi 
Could you provide sample debug output plus XML?

**Comment by dryBoneMarrow** [comment]
Hello, thank you for looking at my issue.
[debug_output.txt](https://github.com/rbodziony/mcf2pdf/files/14839702/debug_output.txt)
I put the whole output that I got when running with `-d` in this file. I don't know which XML file you mean, can I generate it somehow?

**Comment by rbodziony** [comment]
hi founded issue 
thx for rising 
check if it works  now 
 https://github.com/rbodziony/mcf2pdf/releases/tag/0.7.5.beta1

**Comment by dryBoneMarrow** [comment]
Tysm, it works fine now, no problems at all.
