### ISSUE TITLE
java.lang.ClassCastException: org.jsoup.nodes.TextNode cannot be cast to org.jsoup.nodes.Element

### ISSUE THREAD

**Issue by martind1983** [rbodziony/mcf2pdf#8]
Following error after start of mcf2pdf:

[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.ClassCastException: org.jsoup.nodes.TextNode cannot be cast to org.jsoup.nodes.Element
        at net.sf.mcf2pdf.pagebuild.PageText.parseText(PageText.java:107)
        at net.sf.mcf2pdf.pagebuild.PageText.<init>(PageText.java:59)
        at net.sf.mcf2pdf.Mcf2FoConverter.processDoublePage(Mcf2FoConverter.java:293)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:221)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Win 10
Cewe Fotobuch
mcf2pdf 0.3.5

Thanks for your support :-)

Debug attached: 
[debug 0.3.5 log.txt](https://github.com/rbodziony/mcf2pdf/files/2216140/debug.0.3.5.log.txt)

**Comment by rbodziony** [comment]
i need couple 1st pages from this mcf file

**Comment by martind1983** [comment]
there you go: [FB_Part1.zip](https://github.com/rbodziony/mcf2pdf/files/2220637/FB_Part1.zip)

**Comment by rbodziony** [comment]
replace jar from attachment and check again 
[mcf2pdf-0.3.5-SNAPSHOT.jar.zip](https://github.com/rbodziony/mcf2pdf/files/2222139/mcf2pdf-0.3.5-SNAPSHOT.jar.zip)

**Comment by martind1983** [comment]
sorry, what exactly do I need to change / replace?

**Comment by rbodziony** [comment]
In folder where you have unzipped mcf2pdf there is jar file replace this jar from jar unzipped from attachment, you may need to renamed it

**Comment by rbodziony** [comment]
works ?

**Comment by martind1983** [comment]
fist of all thanks for the support and sorry, did not find time earlier. 

could now start converting, but one warning:
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 8: schema_portrait_002

and in the end it stopps with following error:

[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 116+117...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
javax.imageio.IIOException: Unsupported JPEG process: SOF type 0xcf
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.internalRead(ImageUtil.java:337)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:91)
        at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:101)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:253)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

Debug attached: 
[debug_2018-07-31.txt](https://github.com/rbodziony/mcf2pdf/files/2247197/debug_2018-07-31.txt)

**Comment by rbodziony** [comment]
[mcf2pdf-0.3.5-SNAPSHOT.zip](https://github.com/rbodziony/mcf2pdf/files/2257412/mcf2pdf-0.3.5-SNAPSHOT.zip)

try with this file (same procedure as above)

**Comment by martind1983** [comment]
thank you very much - worked :) :) great support!
